### ISSUE TITLE
Adapt to big screens

### ISSUE THREAD

**Issue by orpgol** [shenkarlab/pensyaTeam#14]
Because of design constraints, our project is adapted to a 13" screen with percentages, but breaks on different resolutions...

we would like to keep the same design but adapt automatically to different (Big Screen) resolutions.

**Comment by orpgol** [comment]
@chen1203 
@mushon 
@akariv

**Comment by mushon** [comment]
this should basically be addressed by issue #15

**Comment by orpgol** [comment]
@mushon for responsiveness we need a new design (for iphones etc) but big screens are on the same design....
anyway, i think i fixed big screen issue, see if you can find small bugs that we should fix @Tamary @chen1203 @eyalkim

**Comment by mushon** [comment]
As a fallback, can you support the portrait orientation? it might require less customized development. The more "pressing" issue has to do with hovering, dragging and pressing that should be supported in touch screens and were not supported in the latest version.
