### ISSUE TITLE
Project status and updates

### ISSUE THREAD

**Issue by mushon** [shenkarlab/pensyaTeam#5]

**Comment by orpgol** [comment]
Hi,
Codewize, we are working on building functionality of small parts of the data to begin with, plus we started building the parallax website.
Designerwize, the designers are working on high-fidelity wireframes and drafts for the illustrations and trying out graphic styles.

**Comment by mushon** [comment]
Hey there @shenkarlab/pensyonerim,
@akariv will be coming on Sunday and will be able to sit and instruct the tech teams. If you want his help you will need to describe the issues at hand in details. Only the issues that are ready, detailed, refer to specific code, examples and all will be addressed first. We will not have time to waste on half-baked questions so if you want Adam's help you need to prepare yourselves towards it, and if you don't need any technical help at this point, that's also fine.
In case you want to meet Adam, **make a detailed tickets (or more than one) and assign them to @akariv for feedback**. He will choose who to sit with and who not to based on the details and depth of your questions.
Good luck!
